export const FETCH_ALL_MESSAGES_INITIATED = 'FETCH_ALL_MESSAGES_INITIATED';
export const FETCH_ALL_MESSAGES_SUCCESS = 'FETCH_ALL_MESSAGES_SUCCESS';
export const FETCH_ALL_MESSAGES_FAIL = 'FETCH_ALL_MESSAGES_FAIL';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const FETCH_ALL_USERS_INITIATED = 'FETCH_ALL_USERS_INITIATED';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAIL = 'FETCH_ALL_USERS_FAIL';
